# Generated by Django 4.1 on 2022-08-09 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RemoveField(
            model_name="discount",
            name="ends",
        ),
        migrations.AddField(
            model_name="discount",
            name="end_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Expiry date"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="start_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Start date"
            ),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="first_name",
            field=models.CharField(max_length=30, verbose_name="First name"),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="Last name"),
        ),
    ]
