# Generated by Django 4.1 on 2022-08-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_category_options_remove_discount_ends_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Available quantity"
            ),
        ),
    ]
