# Generated by Django 4.1 on 2022-08-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_image_alter_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2,
                default=5,
                max_digits=10,
                verbose_name="Original Price",
            ),
            preserve_default=False,
        ),
    ]
