# Generated by Django 4.1 on 2022-08-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Stock keeping unit",
            ),
        ),
    ]
