# Generated by Django 4.1 on 2022-08-09 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_groups_customuser_user_permissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
