# Generated by Django 4.1 on 2022-08-21 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="responsible_cashier",
            field=models.ForeignKey(
                default=1,
                limit_choices_to={"is_cashier": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Responsible Cashier",
            ),
            preserve_default=False,
        ),
    ]
