# Generated by Django 4.1 on 2022-08-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_order_responsible_cashier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="paid",
        ),
    ]
